from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass
from enum import Enum
from typing import Callable


SUPPORTED_LANGUAGES = ("ru", "en")
DEFAULT_LANGUAGE = "ru"


@dataclass(frozen=True, slots=True)
class LanguageOption:
    code: str
    label: str


class MessageSeverity(str, Enum):
    ERROR = "error"
    WARNING = "warning"


class LocalizationService:
    """Provides application-level translations and lightweight message localization."""

    def __init__(self, language: str = DEFAULT_LANGUAGE) -> None:
        self._language = language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE

    @property
    def language(self) -> str:
        return self._language

    def set_language(self, language: str) -> None:
        self._language = language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE

    def language_options(self) -> list[LanguageOption]:
        return [
            LanguageOption(code=code, label=self.text(f"language.option.{code}"))
            for code in SUPPORTED_LANGUAGES
        ]

    def text(self, key: str, **kwargs: object) -> str:
        catalog = _TRANSLATIONS.get(self._language, _TRANSLATIONS[DEFAULT_LANGUAGE])
        template = catalog.get(key, _TRANSLATIONS["en"].get(key, key))
        return template.format(**kwargs)

    def bool_text(self, value: bool) -> str:
        return self.text("common.enabled" if value else "common.disabled")

    def severity_text(self, severity: str) -> str:
        mapping = {
            MessageSeverity.ERROR.value: "severity.error",
            MessageSeverity.WARNING.value: "severity.warning",
        }
        return self.text(mapping.get(severity, severity))

    def simulation_status_text(self, status: str) -> str:
        return self.text(f"simulation.status.{status}")

    def simulation_mode_text(self, mode: str) -> str:
        return self.text(f"simulation.mode.{mode}")

    def translate_message(self, message: str) -> str:
        if self._language == "en":
            return message

        stripped = message.strip()
        if not stripped:
            return message

        if "; " in stripped:
            return "; ".join(self.translate_message(part) for part in stripped.split("; "))

        issue_match = re.match(r"^(error|warning): ([^-]+) - (.+)$", stripped)
        if issue_match:
            severity, path, tail = issue_match.groups()
            return f"{self.severity_text(severity)}: {path} - {self.translate_message(tail)}"

        path_match = re.match(r"^([A-Za-z0-9_.\\[\\]]+): (.+)$", stripped)
        if path_match:
            path, tail = path_match.groups()
            return f"{path}: {self.translate_message(tail)}"

        exact = _EXTERNAL_EXACT_TRANSLATIONS_RU.get(stripped)
        if exact is not None:
            return exact

        for pattern, key, builder in _EXTERNAL_PATTERN_TRANSLATIONS_RU:
            match = pattern.match(stripped)
            if match is not None:
                return self.text(key, **builder(match))

        return message


def _identity_builder(match: re.Match[str]) -> Mapping[str, object]:
    return {}


_TRANSLATIONS: dict[str, dict[str, str]] = {
    "ru": {},
    "en": {},
}

_EXTERNAL_EXACT_TRANSLATIONS_RU: dict[str, str] = {
    "Project name must not be empty.": "Название проекта не должно быть пустым.",
    "Model title is empty. The generated input should usually include a title.": "Заголовок модели пуст. Сгенерированный input обычно должен содержать заголовок.",
    "PML cell counts must be zero or positive integers.": "Количество ячеек PML должно быть целым числом не меньше нуля.",
    "Material identifiers must be unique.": "Идентификаторы материалов должны быть уникальными.",
    "Waveform identifiers must be unique.": "Идентификаторы waveform должны быть уникальными.",
    "Receiver identifiers must be unique when provided.": "Идентификаторы приёмников должны быть уникальными, если они заданы.",
    "Source identifiers must be unique when provided.": "Идентификаторы источников должны быть уникальными, если они заданы.",
    "Material identifier must not be empty.": "Идентификатор материала не должен быть пустым.",
    "Waveform identifier must not be empty.": "Идентификатор waveform не должен быть пустым.",
    "Waveform kind must not be empty.": "Тип waveform не должен быть пустым.",
    "Source axis must be one of x, y, or z.": "Ось источника должна быть одной из: x, y или z.",
    "Source identifier must not be blank when provided.": "Идентификатор источника не должен быть пустым, если он задан.",
    "Source has no waveform reference yet.": "У источника пока нет ссылки на waveform.",
    "Source delay must be zero or greater.": "Задержка источника должна быть не меньше нуля.",
    "Source resistance must be greater than zero when provided.": "Сопротивление источника должно быть больше нуля, если оно задано.",
    "Geometry objects must reference at least one material.": "Геометрические объекты должны ссылаться хотя бы на один материал.",
    "No sources are defined yet. The project can be saved but cannot run a full simulation.": "Источники пока не заданы. Проект можно сохранить, но полноценный запуск симуляции невозможен.",
    "No receivers are defined yet. Results collection is not configured.": "Приёмники пока не заданы. Сбор результатов не настроен.",
    "GPU and MPI options are configured together. This is left as an advanced/future-ready path and may require environment-specific tuning.": "Параметры GPU и MPI заданы одновременно. Это оставлено как advanced/future-ready сценарий и может потребовать настройки под конкретное окружение.",
    "Geometry-only mode is enabled but no geometry views are configured.": "Включён режим только геометрии, но geometry views не настроены.",
    "The number of model runs must be at least 1.": "Количество прогонов модели должно быть не меньше 1.",
    "Restart model index must be at least 1.": "Индекс перезапуска модели должен быть не меньше 1.",
    "MPI tasks must be at least 1 when configured.": "Если задан MPI, число tasks должно быть не меньше 1.",
    "Value must be greater than zero.": "Значение должно быть больше нуля.",
    "Value must be zero or greater.": "Значение должно быть не меньше нуля.",
    "Sphere requires a center vector.": "Для сферы нужно задать вектор центра.",
    "Sphere radius must be greater than zero.": "Радиус сферы должен быть больше нуля.",
    "Cylinder requires start and end vectors.": "Для цилиндра нужно задать векторы начала и конца.",
    "Cylinder start and end positions must differ.": "Начальная и конечная точки цилиндра должны отличаться.",
    "Cylinder radius must be greater than zero.": "Радиус цилиндра должен быть больше нуля.",
    "Object requires lower-left and upper-right vectors.": "Объекту нужны векторы нижнего левого и верхнего правого углов.",
    "Lower bound must be smaller than upper bound.": "Нижняя граница должна быть меньше верхней.",
    "Receiver output component filtering is not emitted yet; Stage 3 generates base #rx commands only.": "Фильтрация output components приёмника пока не генерируется; Stage 3 создаёт только базовые команды #rx.",
    "Geometry-only mode is enabled but no geometry views are defined. gprMax will still process geometry without image outputs.": "Включён режим только геометрии, но geometry views не заданы. gprMax всё равно обработает геометрию, но без изображений.",
    "No waveforms are defined in the project.": "В проекте не заданы waveforms.",
    "No sources are defined in the project.": "В проекте не заданы источники.",
    "No receivers are defined in the project.": "В проекте не заданы приёмники.",
    "Selected dataset is not a 1D A-scan trace. Choose an individual output file for A-scan view.": "Выбранный dataset не является одномерной A-scan трассой. Для A-scan выберите отдельный output-файл.",
    "Selected dataset is not a merged B-scan matrix.": "Выбранный dataset не является объединённой матрицей B-scan.",
    "Result file does not contain the 'rxs' group.": "В файле результата отсутствует группа 'rxs'.",
    "Could not read dataset values.": "Не удалось прочитать значения dataset.",
    "No output files are available for this run.": "Для этого запуска нет output-файлов.",
    "Loaded B-scan from merged output file.": "B-scan загружен из объединённого output-файла.",
    "B-scan preview requires either a merged output file or at least two individual .out traces.": "Для B-scan preview нужен либо объединённый output-файл, либо как минимум две отдельные трассы .out.",
    "B-scan preview is unavailable because the trace lengths are inconsistent across output files.": "B-scan preview недоступен, потому что длины трасс в output-файлах различаются.",
    "B-scan preview is unavailable for the selected receiver/component in this run.": "B-scan preview недоступен для выбранного приёмника/компонента в этом запуске.",
    "Built B-scan preview by stacking individual output files.": "B-scan preview построен путём объединения отдельных output-файлов.",
    "A simulation run is already active.": "Симуляция уже запущена.",
    "Run artifacts were not created.": "Артефакты запуска не были созданы.",
    "gprMax exited with a non-zero status code.": "gprMax завершился с ненулевым кодом возврата.",
    "Simulation preparation failed.": "Не удалось подготовить симуляцию.",
    "B-scan dataset is empty.": "Набор данных B-scan пуст.",
}

_EXTERNAL_PATTERN_TRANSLATIONS_RU: list[
    tuple[re.Pattern[str], str, Callable[[re.Match[str]], Mapping[str, object]]]
] = [
    (re.compile(r"^Waveform kind '(.+)' is outside the current guided editor defaults\.$"), "external.waveform_kind_outside_defaults", lambda match: {"kind": match.group(1)}),
    (re.compile(r"^Source kind '(.+)' is not supported by the current editor\.$"), "external.source_kind_not_supported_editor", lambda match: {"kind": match.group(1)}),
    (re.compile(r"^Waveform '(.+)' is not defined in this project\.$"), "external.waveform_not_defined", lambda match: {"waveform_id": match.group(1)}),
    (re.compile(r"^Geometry kind '(.+)' is not supported by the current editor\.$"), "external.geometry_kind_not_supported_editor", lambda match: {"kind": match.group(1)}),
    (re.compile(r"^Geometry references unknown material '(.+)'\.$"), "external.geometry_unknown_material", lambda match: {"material_id": match.group(1)}),
    (re.compile(r"^Source kind '(.+)' is not supported by the current input generator\.$"), "external.source_kind_not_supported_generator", lambda match: {"kind": match.group(1)}),
    (re.compile(r"^Geometry kind '(.+)' is not supported by the current input generator\.$"), "external.geometry_kind_not_supported_generator", lambda match: {"kind": match.group(1)}),
    (re.compile(r"^Coordinate must be within the domain range 0\\.\\.(.+)\\.$"), "external.coordinate_out_of_domain", lambda match: {"limit": match.group(1)}),
    (re.compile(r"^Bounds must lie within the domain range 0\\.\\.(.+)\\.$"), "external.bounds_out_of_domain", lambda match: {"limit": match.group(1)}),
    (re.compile(r"^Unsupported source kind '(.+)'\.$"), "external.unsupported_source_kind", lambda match: {"kind": match.group(1)}),
    (re.compile(r"^Unsupported geometry primitive '(.+)'\.$"), "external.unsupported_geometry_kind", lambda match: {"kind": match.group(1)}),
    (re.compile(r"^Geometry '(.+)' is missing the '(.+)' vector parameter\.$"), "external.geometry_missing_parameter", lambda match: {"kind": match.group(1), "parameter": match.group(2)}),
    (re.compile(r"^Geometry '(.+)' does not reference a material\.$"), "external.geometry_missing_material", lambda match: {"kind": match.group(1)}),
    (re.compile(r"^Receiver '(.+)' was not found in (.+)\.$"), "external.receiver_not_found", lambda match: {"receiver_id": match.group(1), "path": match.group(2)}),
    (re.compile(r"^Component '(.+)' is not available for receiver '(.+)'\.$"), "external.component_not_available", lambda match: {"component": match.group(1), "receiver_id": match.group(2)}),
    (re.compile(r"^Dataset rxs/(.+?)/(.+) is missing\.$"), "external.dataset_missing", lambda match: {"receiver_id": match.group(1), "component": match.group(2)}),
    (re.compile(r"^Result file does not exist: (.+)$"), "external.result_file_missing", lambda match: {"path": match.group(1)}),
    (re.compile(r"^Could not open HDF5 result file: (.+)$"), "external.result_file_open_failed", lambda match: {"path": match.group(1)}),
    (re.compile(r"^Results viewing requires the 'h5py' package\\.(.+)$"), "external.h5py_required", _identity_builder),
    (re.compile(r"^Python executable not found: (.+)$"), "external.python_not_found", lambda match: {"path": match.group(1)}),
    (re.compile(r"^Timed out while checking the gprMax runtime\\.$"), "external.runtime_probe_timeout", _identity_builder),
    (re.compile(r"^gprMax module '(.+)' is not available in (.+)\.$"), "external.gprmax_module_missing", lambda match: {"module_name": match.group(1), "runtime": match.group(2)}),
]

_TRANSLATIONS["ru"].update(
    {
        "external.waveform_kind_outside_defaults": "Тип waveform '{kind}' выходит за пределы текущих guided defaults редактора.",
        "external.source_kind_not_supported_editor": "Тип источника '{kind}' не поддерживается текущим редактором.",
        "external.waveform_not_defined": "Waveform '{waveform_id}' не определён в этом проекте.",
        "external.geometry_kind_not_supported_editor": "Тип геометрии '{kind}' не поддерживается текущим редактором.",
        "external.geometry_unknown_material": "Геометрия ссылается на неизвестный материал '{material_id}'.",
        "external.source_kind_not_supported_generator": "Тип источника '{kind}' не поддерживается текущим генератором input.",
        "external.geometry_kind_not_supported_generator": "Тип геометрии '{kind}' не поддерживается текущим генератором input.",
        "external.coordinate_out_of_domain": "Координата должна находиться в пределах области 0..{limit}.",
        "external.bounds_out_of_domain": "Границы должны находиться в пределах области 0..{limit}.",
        "external.unsupported_source_kind": "Неподдерживаемый тип источника '{kind}'.",
        "external.unsupported_geometry_kind": "Неподдерживаемый геометрический примитив '{kind}'.",
        "external.geometry_missing_parameter": "У геометрии '{kind}' отсутствует векторный параметр '{parameter}'.",
        "external.geometry_missing_material": "Геометрия '{kind}' не ссылается на материал.",
        "external.receiver_not_found": "Приёмник '{receiver_id}' не найден в {path}.",
        "external.component_not_available": "Компонент '{component}' недоступен для приёмника '{receiver_id}'.",
        "external.dataset_missing": "Dataset rxs/{receiver_id}/{component} отсутствует.",
        "external.result_file_missing": "Файл результата не существует: {path}",
        "external.result_file_open_failed": "Не удалось открыть HDF5-файл результата: {path}",
        "external.h5py_required": "Для просмотра результатов нужен пакет 'h5py'. Установите зависимости проекта или запускайте приложение в том же Python environment, что и gprMax.",
        "external.python_not_found": "Python executable не найден: {path}",
        "external.runtime_probe_timeout": "Проверка runtime gprMax завершилась по таймауту.",
        "external.gprmax_module_missing": "Модуль gprMax '{module_name}' недоступен в {runtime}.",
    }
)

_EXTERNAL_EXACT_TRANSLATIONS_RU.update(
    {
        "Using bundled engine from the installation directory.": "Используется встроенное ядро из каталога установки.",
        "Using configured external fallback runtime.": "Используется внешний fallback runtime, указанный в настройках.",
        "Using current Python interpreter as a development fallback.": "Используется текущий интерпретатор Python как fallback для режима разработки.",
        "Timed out while checking the gprMax runtime.": "Проверка runtime gprMax завершилась по таймауту.",
        "Could not parse runtime probe output.": "Не удалось разобрать результат проверки runtime.",
        "gprMax runtime probe failed.": "Проверка runtime gprMax завершилась с ошибкой.",
    }
)

_EXTERNAL_PATTERN_TRANSLATIONS_RU.extend(
    [
        (
            re.compile(r"^Bundled engine was not found at expected path: (.+)$"),
            "external.bundled_engine_missing",
            lambda match: {"path": match.group(1)},
        ),
        (
            re.compile(r"^Bundled engine directory is missing: (.+)$"),
            "external.bundled_engine_directory_missing",
            lambda match: {"path": match.group(1)},
        ),
        (
            re.compile(r"^Bundled engine manifest is missing: (.+)$"),
            "external.bundled_engine_manifest_missing",
            lambda match: {"path": match.group(1)},
        ),
    ]
)

_TRANSLATIONS["ru"].update(
    {
        "external.bundled_engine_missing": "Встроенное ядро не найдено по ожидаемому пути: {path}",
        "external.bundled_engine_directory_missing": "Каталог встроенного ядра отсутствует: {path}",
        "external.bundled_engine_manifest_missing": "Manifest встроенного ядра отсутствует: {path}",
        "settings.runtime_section": "Текущая runtime-конфигурация",
        "settings.capabilities_section": "Доступные возможности",
        "settings.diagnostics_section": "Диагностика",
        "settings.runtime_mode": "Режим runtime",
        "settings.runtime_mode.bundled": "Встроенный",
        "settings.runtime_mode.external": "Внешний fallback",
        "settings.install_root": "Каталог установки",
        "settings.engine_root": "Каталог ядра",
        "settings.python_executable": "Python executable",
        "settings.app_version": "Версия приложения",
        "settings.engine_version": "Версия engine bundle",
        "settings.gprmax_version_label": "Версия gprMax",
        "settings.cache_directory": "Каталог кэша",
        "settings.temp_directory": "Временный каталог",
        "settings.external_runtime_executable": "Внешний fallback Python executable",
        "settings.external_runtime_placeholder": "Необязательно. Используется только в advanced/debug fallback-сценариях.",
        "settings.diagnostics_placeholder": "Диагностических замечаний нет.",
        "settings.capability.cpu": "CPU",
        "settings.capability.gpu": "GPU",
        "settings.capability.mpi": "MPI",
        "settings.capability_status.ready": "готово",
        "settings.capability_status.optional": "опционально",
        "settings.capability_status.unavailable": "недоступно",
        "settings.summary.settings_file": "Файл настроек",
        "settings.summary.logs_directory": "Каталог логов",
    }
)

_TRANSLATIONS["en"].update(
    {
        "settings.runtime_section": "Current runtime",
        "settings.capabilities_section": "Capabilities",
        "settings.diagnostics_section": "Diagnostics",
        "settings.runtime_mode": "Runtime mode",
        "settings.runtime_mode.bundled": "Bundled",
        "settings.runtime_mode.external": "External fallback",
        "settings.install_root": "Installation root",
        "settings.engine_root": "Engine root",
        "settings.python_executable": "Python executable",
        "settings.app_version": "App version",
        "settings.engine_version": "Engine bundle version",
        "settings.gprmax_version_label": "gprMax version",
        "settings.cache_directory": "Cache directory",
        "settings.temp_directory": "Temporary directory",
        "settings.external_runtime_executable": "External fallback Python executable",
        "settings.external_runtime_placeholder": "Optional. Used only for advanced/debug fallback scenarios.",
        "settings.diagnostics_placeholder": "No runtime diagnostics to show.",
        "settings.capability.cpu": "CPU",
        "settings.capability.gpu": "GPU",
        "settings.capability.mpi": "MPI",
        "settings.capability_status.ready": "ready",
        "settings.capability_status.optional": "optional",
        "settings.capability_status.unavailable": "unavailable",
        "settings.summary.settings_file": "Settings file",
        "settings.summary.logs_directory": "Logs directory",
    }
)

_TRANSLATIONS["ru"].update(
    {
        "app.name": "GPRMax Workbench",
        "common.add": "Добавить",
        "common.duplicate": "Дублировать",
        "common.delete": "Удалить",
        "common.save": "Сохранить",
        "common.browse": "Обзор...",
        "common.enabled": "Включено",
        "common.disabled": "Выключено",
        "common.not_set": "Не задано",
        "severity.error": "ошибка",
        "severity.warning": "предупреждение",
        "language.label": "Язык интерфейса",
        "language.option.ru": "Русский",
        "language.option.en": "Английский",
        "menu.file": "Файл",
        "menu.help": "Справка",
        "action.new_project": "Новый проект",
        "action.open_project": "Открыть проект",
        "action.save_project": "Сохранить проект",
        "action.about": "О программе",
        "sidebar.title": "GPRMax\nWorkbench",
        "sidebar.subtitle": "Desktop-приложение для управляемого моделирования и запуска симуляций gprMax.",
        "status.stage_ready": "Готова основа Stage 5: редактор модели, запуск симуляций и просмотр результатов.",
        "page.welcome.title": "Старт",
        "page.welcome.description": "Менеджер проектов и стартовая точка работы.",
        "page.project.title": "Редактор модели",
        "page.project.description": "Формы для настройки модели, материалов, сущностей и preview входного файла.",
        "page.simulation.title": "Симуляция",
        "page.simulation.description": "Генерация input, запуск, логи и история прогонов.",
        "page.results.title": "Результаты",
        "page.results.description": "Просмотр результатов запусков, метаданных и A-scan/B-scan preview.",
        "page.settings.title": "Настройки",
        "page.settings.description": "Настройки приложения и runtime-среды.",
        "about.title": "О программе GPRMax Workbench",
        "about.body": "Основа Stage 5: MVP-редактор модели, subprocess-запуск, артефакты прогонов и просмотр результатов с A-scan/B-scan preview.",
        "dialog.new_project.title": "Новый проект",
        "dialog.new_project.intro": "Создать корневую папку проекта с manifest-файлом и стандартными каталогами generated/runs/results/assets.",
        "dialog.new_project.project_name": "Название проекта",
        "dialog.new_project.project_directory": "Каталог проекта",
        "dialog.new_project.choose_directory": "Выберите каталог проекта",
        "dialog.new_project.name_required": "Нужно указать название проекта.",
        "dialog.new_project.directory_required": "Нужно указать каталог проекта.",
        "welcome.title": "Добро пожаловать",
        "welcome.subtitle": "Создайте новый проект, откройте существующий или продолжите работу из списка недавних проектов. Это основная точка входа для пользователей без навыков программирования.",
        "welcome.current_project": "Текущий проект",
        "welcome.recent_projects": "Недавние проекты",
        "welcome.no_project": "Сейчас проект не открыт.",
        "welcome.no_recent_projects": "Недавних проектов пока нет.",
        "welcome.current_project_details": "{name}\nПуть: {path}\nЗаголовок модели: {model_title}",
        "project.title": "Редактор модели",
        "project.subtitle": "Stage 4 добавляет form-based редактор для практичного MVP-подмножества gprMax: базовые параметры модели, материалы, waveforms, источники, приёмники, геометрия и preview входного файла.",
        "project.workspace": "Рабочая область проекта",
        "project.no_project": "Проект не открыт",
        "project.manifest": "Manifest: {path}",
        "project.summary.empty": "Откройте или создайте проект, чтобы редактировать сущности модели gprMax.",
        "project.validation.empty": "Валидация: проект не загружен.",
        "project.summary.editing": "Редактируется «{name}». Материалы: {materials}, геометрия: {geometry}, источники: {sources}, приёмники: {receivers}.",
        "project.validation.clean": "{state} Валидация: проблем нет.",
        "project.validation.summary": "{state} Валидация: {errors} ошибк(и), {warnings} предупреждени(й).",
        "project.state.saved": "Сохранено.",
        "project.state.unsaved": "Есть несохранённые изменения.",
        "project.tab.general": "Общее",
        "project.tab.materials": "Материалы",
        "project.tab.waveforms": "Waveforms",
        "project.tab.sources": "Источники",
        "project.tab.receivers": "Приёмники",
        "project.tab.geometry": "Геометрия",
        "project.tab.preview": "Input Preview",
        "settings.title": "Настройки",
        "settings.subtitle": "Сохранение настроек приложения: advanced mode, язык интерфейса и Python-интерпретатор для запуска gprMax.",
        "settings.advanced_mode": "Включить advanced mode",
        "settings.save": "Сохранить настройки",
        "settings.runtime_executable": "Python executable для gprMax",
        "settings.summary.settings_file": "Файл настроек",
        "settings.summary.logs_directory": "Каталог логов",
        "settings.summary.gprmax_runtime": "Runtime gprMax",
        "settings.summary.advanced_mode": "Advanced mode",
        "settings.summary.recent_projects": "Недавние проекты",
        "settings.summary.interface_language": "Язык интерфейса",
        "simulation.title": "Запуск симуляции",
        "simulation.subtitle": "Stage 3 добавляет генерацию input, subprocess-запуск, live-логи и историю прогонов. Экран сознательно сфокусирован на надёжном execution flow.",
        "simulation.no_project": "Проект не загружен.",
        "simulation.no_run_prepared": "Запуск не подготовлен.",
        "simulation.validation_placeholder": "Здесь будут показаны сообщения валидации.",
        "simulation.preview_placeholder": "Сгенерированный input gprMax появится здесь",
        "simulation.log_placeholder": "Здесь появится live stdout/stderr",
        "simulation.project_state": "Проект: {name} ({state})",
        "simulation.project_state.saved": "сохранён",
        "simulation.project_state.dirty": "есть несохранённые изменения",
        "simulation.run_state.none": "Нет активного запуска.",
        "simulation.run_state.active": "Запуск {run_id}: {status}",
        "simulation.runtime_card": "Контекст запуска",
        "simulation.config_card": "Конфигурация запуска",
        "simulation.history_card": "История прогонов",
        "simulation.preview_card": "Input preview",
        "simulation.log_card": "Live log output",
        "simulation.runtime": "Runtime",
        "simulation.project_state_label": "Состояние проекта",
        "simulation.run_state_label": "Состояние запуска",
        "simulation.messages": "Сообщения",
        "simulation.mode": "Режим",
        "simulation.gpu": "Использовать GPU",
        "simulation.gpu_devices": "Идентификаторы GPU",
        "simulation.gpu_devices_placeholder": "Необязательно, например: 0 1",
        "simulation.num_runs": "Прогоны модели (-n)",
        "simulation.restart": "Перезапуск модели (-restart)",
        "simulation.mpi_tasks": "MPI tasks (-mpi)",
        "simulation.geometry_fixed": "Фиксированная геометрия",
        "simulation.write_processed": "Сохранить processed input",
        "simulation.benchmark": "Режим benchmark",
        "simulation.mpi_no_spawn": "MPI no spawn",
        "simulation.extra_args": "Доп. аргументы CLI",
        "simulation.extra_args_placeholder": "Необязательные raw CLI args",
        "simulation.action.preview": "Построить preview",
        "simulation.action.export": "Экспорт input",
        "simulation.action.start": "Запустить",
        "simulation.action.cancel": "Отменить запуск",
        "simulation.action.open_run": "Открыть папку запуска",
        "simulation.action.open_output": "Открыть папку output",
        "simulation.mode.normal": "Обычный запуск",
        "simulation.mode.geometry_only": "Только геометрия",
        "simulation.status.pending": "ожидание",
        "simulation.status.preparing": "подготовка",
        "simulation.status.running": "выполняется",
        "simulation.status.completed": "завершён",
        "simulation.status.failed": "ошибка",
        "simulation.status.cancelled": "отменён",
        "results.title": "Просмотр результатов",
        "results.subtitle": "Stage 5 сфокусирован на обнаружении результатов по запускам, метаданных, A-scan и ограниченном workflow для B-scan preview.",
        "results.status.open_project": "Откройте проект и выберите завершённый запуск, чтобы посмотреть результаты.",
        "results.status.select_run": "Выберите запуск, чтобы посмотреть результаты.",
        "results.status.select_output": "Выберите output-файл для просмотра.",
        "results.status.no_results": "Для этого проекта результаты запусков пока не найдены.",
        "results.status.no_output_files": "Для этого запуска нет output-файлов.",
        "results.status.no_receivers": "В выбранном output-файле не найдено приёмников.",
        "results.status.no_components": "У выбранного приёмника нет доступных output components.",
        "results.status.select_trace": "Выберите output-файл, приёмник и компонент.",
        "results.action.refresh": "Обновить результаты",
        "results.action.open_output": "Открыть папку output",
        "results.action.open_selected": "Открыть выбранный файл",
        "results.card.runs": "Запуски",
        "results.card.summary": "Сводка",
        "results.card.output_files": "Output-файлы",
        "results.card.other_artifacts": "Другие артефакты",
        "results.receiver": "Приёмник",
        "results.component": "Компонент",
        "results.tab.ascan": "A-scan",
        "results.tab.bscan": "B-scan",
        "results.run_item": "{run_id} | {status}",
        "results.receiver_item": "{receiver_id} | {name}",
        "results.ascan_loaded": "A-scan загружен: {samples} samples, dt={dt:.6g} s.",
        "results.summary.run_id": "Run ID",
        "results.summary.status": "Статус",
        "results.summary.created": "Создан",
        "results.summary.finished": "Завершён",
        "results.summary.duration": "Длительность",
        "results.summary.input_file": "Input file",
        "results.summary.output_file": "Output file",
        "results.summary.model_title": "Заголовок модели",
        "results.summary.receivers": "Приёмники",
        "results.summary.components": "Компоненты",
        "results.summary.grid": "Сетка",
        "results.summary.dt": "dt",
        "results.summary.notes": "Примечания",
        "results.summary.select_run": "Выберите завершённый запуск, чтобы посмотреть результаты.",
        "results.summary.no_issues": "Проблем с результатами не обнаружено.",
        "results.plot.ascan_title": "A-scan",
        "results.plot.ascan_prompt": "Выберите запуск, output-файл, приёмник и компонент, чтобы посмотреть A-scan.",
        "results.plot.time_ns": "Время (нс)",
        "results.plot.ascan_chart_title": "A-scan | {receiver_name} | {component}",
        "results.plot.bscan_placeholder": "B-scan preview появится здесь, когда выбранный запуск это поддерживает.",
        "results.plot.bscan_empty": "Набор данных B-scan пуст.",
        "editor.general.tags_placeholder": "Теги через запятую",
        "editor.general.validation_placeholder": "Здесь появится валидация общих настроек.",
        "editor.general.metadata_group": "Проект и модель",
        "editor.general.project_name": "Название проекта",
        "editor.general.description": "Описание",
        "editor.general.model_title": "Заголовок модели",
        "editor.general.model_notes": "Заметки по модели",
        "editor.general.tags": "Теги",
        "editor.general.domain_group": "Базовая настройка gprMax",
        "editor.general.domain_size": "Размер области (м)",
        "editor.general.resolution": "Шаг сетки (м)",
        "editor.general.time_window": "Временное окно (с)",
        "editor.general.open_project": "Откройте или создайте проект, чтобы редактировать общие настройки.",
        "editor.general.valid": "Общие настройки выглядят согласованно.",
        "editor.materials.list_title": "Материалы",
        "editor.materials.select": "Выберите материал для редактирования.",
        "editor.materials.identifier": "Идентификатор",
        "editor.materials.relative_permittivity": "Относительная диэлектрическая проницаемость",
        "editor.materials.conductivity": "Проводимость",
        "editor.materials.relative_permeability": "Относительная магнитная проницаемость",
        "editor.materials.magnetic_loss": "Магнитные потери",
        "editor.materials.notes": "Заметки",
        "editor.materials.tags": "Теги",
        "editor.materials.valid": "Проблем по материалам не найдено.",
        "editor.materials.unnamed": "<без имени>",
        "editor.waveforms.list_title": "Waveforms",
        "editor.waveforms.select": "Выберите waveform для редактирования.",
        "editor.waveforms.identifier": "Идентификатор",
        "editor.waveforms.kind": "Тип",
        "editor.waveforms.amplitude": "Амплитуда",
        "editor.waveforms.center_frequency": "Центральная частота (Гц)",
        "editor.waveforms.notes": "Заметки",
        "editor.waveforms.tags": "Теги",
        "editor.waveforms.valid": "Проблем по waveform не найдено.",
        "editor.waveforms.unnamed": "<без имени>",
        "editor.sources.list_title": "Источники / передатчики",
        "editor.sources.select": "Выберите источник для редактирования.",
        "editor.sources.identifier": "Идентификатор",
        "editor.sources.kind": "Тип",
        "editor.sources.axis": "Ось",
        "editor.sources.waveform": "Waveform",
        "editor.sources.position_x": "Позиция X (м)",
        "editor.sources.position_y": "Позиция Y (м)",
        "editor.sources.position_z": "Позиция Z (м)",
        "editor.sources.delay": "Задержка (с)",
        "editor.sources.resistance": "Сопротивление (Ом)",
        "editor.sources.notes": "Заметки",
        "editor.sources.tags": "Теги",
        "editor.sources.no_waveform": "<нет>",
        "editor.sources.no_waveform_item": "без waveform",
        "editor.sources.resistance_placeholder": "Необязательно; по умолчанию 50 Ом для voltage source",
        "editor.sources.valid": "Проблем по источникам не найдено.",
        "editor.receivers.list_title": "Приёмники",
        "editor.receivers.select": "Выберите приёмник для редактирования.",
        "editor.receivers.identifier": "Идентификатор",
        "editor.receivers.position_x": "Позиция X (м)",
        "editor.receivers.position_y": "Позиция Y (м)",
        "editor.receivers.position_z": "Позиция Z (м)",
        "editor.receivers.outputs": "Выходы",
        "editor.receivers.outputs_placeholder": "Компоненты через запятую, например: Ez, Ex",
        "editor.receivers.notes": "Заметки",
        "editor.receivers.tags": "Теги",
        "editor.receivers.valid": "Проблем по приёмникам не найдено.",
        "editor.receivers.default_name": "receiver",
        "editor.geometry.list_title": "Геометрические объекты",
        "editor.geometry.select": "Выберите геометрический объект для редактирования.",
        "editor.geometry.label": "Метка",
        "editor.geometry.kind": "Тип",
        "editor.geometry.material": "Материал",
        "editor.geometry.smoothing": "Использовать dielectric smoothing",
        "editor.geometry.parameters": "Параметры",
        "editor.geometry.notes": "Заметки",
        "editor.geometry.tags": "Теги",
        "editor.geometry.valid": "Проблем по геометрии не найдено.",
        "editor.geometry.no_material": "без материала",
        "editor.geometry.box.lower_left_x": "Нижний левый X",
        "editor.geometry.box.lower_left_y": "Нижний левый Y",
        "editor.geometry.box.lower_left_z": "Нижний левый Z",
        "editor.geometry.box.upper_right_x": "Верхний правый X",
        "editor.geometry.box.upper_right_y": "Верхний правый Y",
        "editor.geometry.box.upper_right_z": "Верхний правый Z",
        "editor.geometry.sphere.center_x": "Центр X",
        "editor.geometry.sphere.center_y": "Центр Y",
        "editor.geometry.sphere.center_z": "Центр Z",
        "editor.geometry.radius": "Радиус",
        "editor.geometry.cylinder.start_x": "Начало X",
        "editor.geometry.cylinder.start_y": "Начало Y",
        "editor.geometry.cylinder.start_z": "Начало Z",
        "editor.geometry.cylinder.end_x": "Конец X",
        "editor.geometry.cylinder.end_y": "Конец Y",
        "editor.geometry.cylinder.end_z": "Конец Z",
        "editor.preview.title": "Этот preview строится из текущей in-memory модели с конфигурацией запуска по умолчанию. Runtime-флаги остаются на экране Simulation.",
        "editor.preview.messages_placeholder": "Сообщения валидации и preview",
        "editor.preview.text_placeholder": "Сгенерированный input gprMax появится здесь",
        "editor.preview.rebuild": "Перестроить preview",
        "editor.preview.export": "Экспорт preview",
        "editor.preview.messages": "Сообщения",
        "editor.preview.input": "Input preview",
        "editor.preview.export_dialog": "Экспорт preview",
        "editor.preview.exported": "Preview экспортирован в {destination}",
        "window.title.base": "GPRMax Workbench",
        "window.title.project": "GPRMax Workbench - {project_name}{dirty_marker}{run_suffix}",
        "window.run_suffix": " [{status}: {run_id}]",
        "status.created_project": "Проект «{name}» создан в {root}",
        "status.opened_project": "Проект «{name}» открыт",
        "status.project_saved": "Проект успешно сохранён.{warning_text}",
        "status.project_saved_warnings": " Сохранено с предупреждениями: {warnings}",
        "status.settings_saved": "Настройки сохранены.",
        "status.preview_rebuilt": "Input preview обновлён.",
        "status.input_exported": "Input экспортирован в {destination}",
        "status.run_started": "Запуск {run_id} начат",
        "status.cancellation_requested": "Запрошена отмена запуска.",
        "message.save_project.no_project": "Сначала создайте или откройте проект.",
        "message.simulation.no_project": "Сначала создайте или откройте проект, затем используйте simulation runner.",
        "message.cancel_run.none": "Сейчас нет активного запуска, который можно отменить.",
        "message.open_run_folder.none": "Выберите запуск из истории или сначала запустите симуляцию.",
        "message.open_output_folder.none": "Выберите запуск из истории или сначала запустите симуляцию.",
        "message.start_run.title": "Запуск симуляции",
        "message.input_preview.title": "Input Preview",
        "message.export_input.title": "Экспорт input",
        "message.save_project.title": "Сохранение проекта",
        "message.new_project.title": "Новый проект",
        "message.open_project.title": "Открытие проекта",
        "message.simulation.title": "Симуляция",
        "message.cancel_run.title": "Отмена запуска",
        "message.open_run_folder.title": "Открыть папку запуска",
        "message.open_output_folder.title": "Открыть папку output",
        "dialog.open_project_directory": "Открыть каталог проекта",
        "dialog.export_input": "Экспортировать input gprMax",
        "dialog.export_input_filter": "gprMax input (*.in);;Все файлы (*)",
        "dialog.export_preview_filter": "gprMax input (*.in);;Все файлы (*)",
    }
)

_TRANSLATIONS["en"].update(
    {
        "app.name": "GPRMax Workbench",
        "common.add": "Add",
        "common.duplicate": "Duplicate",
        "common.delete": "Delete",
        "common.save": "Save",
        "common.browse": "Browse...",
        "common.enabled": "Enabled",
        "common.disabled": "Disabled",
        "common.not_set": "Not set",
        "severity.error": "error",
        "severity.warning": "warning",
        "language.label": "Interface language",
        "language.option.ru": "Russian",
        "language.option.en": "English",
        "menu.file": "File",
        "menu.help": "Help",
        "action.new_project": "New Project",
        "action.open_project": "Open Project",
        "action.save_project": "Save Project",
        "action.about": "About",
        "sidebar.title": "GPRMax\nWorkbench",
        "sidebar.subtitle": "Desktop application for guided modelling and gprMax simulation orchestration.",
        "status.stage_ready": "Stage 5 foundation ready for model editing, execution, and result inspection.",
        "page.welcome.title": "Welcome",
        "page.welcome.description": "Project manager and onboarding entrypoint.",
        "page.project.title": "Model Editor",
        "page.project.description": "Form-based editor for model setup, materials, entities, and input preview.",
        "page.simulation.title": "Simulation",
        "page.simulation.description": "Input generation, execution, logs, and run history.",
        "page.results.title": "Results",
        "page.results.description": "Run-centric result browser with metadata and A-scan/B-scan previews.",
        "page.settings.title": "Settings",
        "page.settings.description": "Application and runtime settings.",
        "about.title": "About GPRMax Workbench",
        "about.body": "Stage 5 foundation: model editor MVP, subprocess execution, run artifacts, and results inspection with A-scan/B-scan previews.",
        "dialog.new_project.title": "New Project",
        "dialog.new_project.intro": "Create a project root folder with a project manifest and the standard generated/runs/results/assets directories.",
        "dialog.new_project.project_name": "Project name",
        "dialog.new_project.project_directory": "Project directory",
        "dialog.new_project.choose_directory": "Choose Project Directory",
        "dialog.new_project.name_required": "Project name is required.",
        "dialog.new_project.directory_required": "Project directory is required.",
        "welcome.title": "Welcome",
        "welcome.subtitle": "Create a new project, reopen an existing one, or continue from the recent projects list. This is the non-programmer entrypoint into the workflow.",
        "welcome.current_project": "Current project",
        "welcome.recent_projects": "Recent projects",
        "welcome.no_project": "No project is currently open.",
        "welcome.no_recent_projects": "No recent projects yet.",
        "welcome.current_project_details": "{name}\nPath: {path}\nModel title: {model_title}",
        "project.title": "Model Editor",
        "project.subtitle": "Stage 4 provides a form-based editor for the practical gprMax MVP subset: essential model settings, materials, waveforms, sources, receivers, geometry, and input preview.",
        "project.workspace": "Project workspace",
        "project.no_project": "No project open",
        "project.manifest": "Manifest: {path}",
        "project.summary.empty": "Open or create a project to edit gprMax model entities.",
        "project.validation.empty": "Validation: no project loaded.",
        "project.summary.editing": "Editing '{name}'. Materials: {materials}, Geometry: {geometry}, Sources: {sources}, Receivers: {receivers}.",
        "project.validation.clean": "{state} Validation: no issues.",
        "project.validation.summary": "{state} Validation: {errors} error(s), {warnings} warning(s).",
        "project.state.saved": "Saved.",
        "project.state.unsaved": "Unsaved changes.",
        "project.tab.general": "General",
        "project.tab.materials": "Materials",
        "project.tab.waveforms": "Waveforms",
        "project.tab.sources": "Sources",
        "project.tab.receivers": "Receivers",
        "project.tab.geometry": "Geometry",
        "project.tab.preview": "Input Preview",
        "settings.title": "Settings",
        "settings.subtitle": "Persist application-level preferences such as advanced mode, interface language, and the Python executable used to launch gprMax.",
        "settings.advanced_mode": "Enable advanced mode",
        "settings.save": "Save Settings",
        "settings.runtime_executable": "gprMax Python executable",
        "settings.summary.settings_file": "Settings file",
        "settings.summary.logs_directory": "Logs directory",
        "settings.summary.gprmax_runtime": "gprMax runtime",
        "settings.summary.advanced_mode": "Advanced mode",
        "settings.summary.recent_projects": "Recent projects",
        "settings.summary.interface_language": "Interface language",
        "window.title.base": "GPRMax Workbench",
        "window.title.project": "GPRMax Workbench - {project_name}{dirty_marker}{run_suffix}",
        "window.run_suffix": " [{status}: {run_id}]",
        "status.created_project": "Created project '{name}' at {root}",
        "status.opened_project": "Opened project '{name}'",
        "status.project_saved": "Project saved successfully.{warning_text}",
        "status.project_saved_warnings": " Saved with warnings: {warnings}",
        "status.settings_saved": "Settings saved.",
        "status.preview_rebuilt": "Input preview rebuilt.",
        "status.input_exported": "Exported input to {destination}",
        "status.run_started": "Started run {run_id}",
        "status.cancellation_requested": "Cancellation requested.",
        "message.save_project.no_project": "Create or open a project before saving.",
        "message.simulation.no_project": "Create or open a project before using the simulation runner.",
        "message.cancel_run.none": "There is no active run to cancel.",
        "message.open_run_folder.none": "Select a run from the history or start a run first.",
        "message.open_output_folder.none": "Select a run from the history or start a run first.",
        "message.start_run.title": "Start Run",
        "message.input_preview.title": "Input Preview",
        "message.export_input.title": "Export Input",
        "message.save_project.title": "Save Project",
        "message.new_project.title": "New Project",
        "message.open_project.title": "Open Project",
        "message.simulation.title": "Simulation",
        "message.cancel_run.title": "Cancel Run",
        "message.open_run_folder.title": "Open Run Folder",
        "message.open_output_folder.title": "Open Output Folder",
        "dialog.open_project_directory": "Open Project Directory",
        "dialog.export_input": "Export gprMax Input",
        "dialog.export_input_filter": "gprMax input (*.in);;All files (*)",
        "dialog.export_preview_filter": "gprMax input (*.in);;All files (*)",
        "simulation.title": "Simulation Runner",
        "simulation.subtitle": "Stage 3 adds input generation, subprocess execution, live logs, and run history. The current screen intentionally focuses on reliable execution flow.",
        "simulation.no_project": "No project loaded.",
        "simulation.no_run_prepared": "No run prepared.",
        "simulation.validation_placeholder": "Validation messages will appear here.",
        "simulation.preview_placeholder": "Generated gprMax input preview",
        "simulation.log_placeholder": "Live stdout/stderr output",
        "simulation.project_state": "Project: {name} ({state})",
        "simulation.project_state.saved": "saved",
        "simulation.project_state.dirty": "unsaved changes",
        "simulation.run_state.none": "No active run.",
        "simulation.run_state.active": "Run {run_id}: {status}",
        "simulation.runtime_card": "Execution context",
        "simulation.config_card": "Run configuration",
        "simulation.history_card": "Run history",
        "simulation.preview_card": "Input preview",
        "simulation.log_card": "Live log output",
        "simulation.runtime": "Runtime",
        "simulation.project_state_label": "Project state",
        "simulation.run_state_label": "Run state",
        "simulation.messages": "Messages",
        "simulation.mode": "Mode",
        "simulation.gpu": "Use GPU",
        "simulation.gpu_devices": "GPU device IDs",
        "simulation.gpu_devices_placeholder": "Optional device IDs, e.g. 0 1",
        "simulation.num_runs": "Model runs (-n)",
        "simulation.restart": "Restart model (-restart)",
        "simulation.mpi_tasks": "MPI tasks (-mpi)",
        "simulation.geometry_fixed": "Geometry fixed",
        "simulation.write_processed": "Write processed input",
        "simulation.benchmark": "Benchmark mode",
        "simulation.mpi_no_spawn": "MPI no spawn",
        "simulation.extra_args": "Extra CLI args",
        "simulation.extra_args_placeholder": "Optional raw CLI args",
        "simulation.action.preview": "Build Preview",
        "simulation.action.export": "Export Input",
        "simulation.action.start": "Start Run",
        "simulation.action.cancel": "Cancel Run",
        "simulation.action.open_run": "Open Run Folder",
        "simulation.action.open_output": "Open Output Folder",
        "simulation.mode.normal": "Normal run",
        "simulation.mode.geometry_only": "Geometry-only",
        "simulation.status.pending": "pending",
        "simulation.status.preparing": "preparing",
        "simulation.status.running": "running",
        "simulation.status.completed": "completed",
        "simulation.status.failed": "failed",
        "simulation.status.cancelled": "cancelled",
        "results.title": "Results Viewer",
        "results.subtitle": "Stage 5 focuses on run-centric result discovery, metadata, A-scan viewing, and a bounded B-scan preview workflow.",
        "results.status.open_project": "Open a project and select a completed run to inspect results.",
        "results.status.select_run": "Select a run to inspect results.",
        "results.status.select_output": "Select an output file to inspect it.",
        "results.status.no_results": "No run results were found for this project yet.",
        "results.status.no_output_files": "No output files are available for this run.",
        "results.status.no_receivers": "No receivers were found in the selected output file.",
        "results.status.no_components": "The selected receiver does not expose any output components.",
        "results.status.select_trace": "Select an output file, receiver, and component.",
        "results.action.refresh": "Refresh Results",
        "results.action.open_output": "Open Output Folder",
        "results.action.open_selected": "Open Selected File",
        "results.card.runs": "Runs",
        "results.card.summary": "Summary",
        "results.card.output_files": "Output files",
        "results.card.other_artifacts": "Other artifacts",
        "results.receiver": "Receiver",
        "results.component": "Component",
        "results.tab.ascan": "A-scan",
        "results.tab.bscan": "B-scan",
        "results.run_item": "{run_id} | {status}",
        "results.receiver_item": "{receiver_id} | {name}",
        "results.ascan_loaded": "A-scan loaded: {samples} samples, dt={dt:.6g} s.",
        "results.summary.run_id": "Run ID",
        "results.summary.status": "Status",
        "results.summary.created": "Created",
        "results.summary.finished": "Finished",
        "results.summary.duration": "Duration",
        "results.summary.input_file": "Input file",
        "results.summary.output_file": "Output file",
        "results.summary.model_title": "Model title",
        "results.summary.receivers": "Receivers",
        "results.summary.components": "Components",
        "results.summary.grid": "Grid",
        "results.summary.dt": "dt",
        "results.summary.notes": "Notes",
        "results.summary.select_run": "Select a completed run to inspect results.",
        "results.summary.no_issues": "No result issues detected.",
        "results.plot.ascan_title": "A-scan",
        "results.plot.ascan_prompt": "Select a run, output file, receiver, and component to view an A-scan.",
        "results.plot.time_ns": "Time (ns)",
        "results.plot.ascan_chart_title": "A-scan | {receiver_name} | {component}",
        "results.plot.bscan_placeholder": "B-scan preview will appear here when the selected run supports it.",
        "results.plot.bscan_empty": "B-scan dataset is empty.",
        "editor.general.tags_placeholder": "Comma-separated tags",
        "editor.general.validation_placeholder": "General settings validation will appear here.",
        "editor.general.metadata_group": "Project and model",
        "editor.general.project_name": "Project name",
        "editor.general.description": "Description",
        "editor.general.model_title": "Model title",
        "editor.general.model_notes": "Model notes",
        "editor.general.tags": "Tags",
        "editor.general.domain_group": "Essential gprMax setup",
        "editor.general.domain_size": "Domain size (m)",
        "editor.general.resolution": "Resolution (m)",
        "editor.general.time_window": "Time window (s)",
        "editor.general.open_project": "Open or create a project to edit general settings.",
        "editor.general.valid": "General settings look consistent.",
        "editor.materials.list_title": "Materials",
        "editor.materials.select": "Select a material to edit it.",
        "editor.materials.identifier": "Identifier",
        "editor.materials.relative_permittivity": "Relative permittivity",
        "editor.materials.conductivity": "Conductivity",
        "editor.materials.relative_permeability": "Relative permeability",
        "editor.materials.magnetic_loss": "Magnetic loss",
        "editor.materials.notes": "Notes",
        "editor.materials.tags": "Tags",
        "editor.materials.valid": "No material-specific validation issues.",
        "editor.materials.unnamed": "<unnamed>",
        "editor.waveforms.list_title": "Waveforms",
        "editor.waveforms.select": "Select a waveform to edit it.",
        "editor.waveforms.identifier": "Identifier",
        "editor.waveforms.kind": "Kind",
        "editor.waveforms.amplitude": "Amplitude",
        "editor.waveforms.center_frequency": "Center frequency (Hz)",
        "editor.waveforms.notes": "Notes",
        "editor.waveforms.tags": "Tags",
        "editor.waveforms.valid": "No waveform-specific validation issues.",
        "editor.waveforms.unnamed": "<unnamed>",
        "editor.sources.list_title": "Sources / transmitters",
        "editor.sources.select": "Select a source to edit it.",
        "editor.sources.identifier": "Identifier",
        "editor.sources.kind": "Kind",
        "editor.sources.axis": "Axis",
        "editor.sources.waveform": "Waveform",
        "editor.sources.position_x": "Position X (m)",
        "editor.sources.position_y": "Position Y (m)",
        "editor.sources.position_z": "Position Z (m)",
        "editor.sources.delay": "Delay (s)",
        "editor.sources.resistance": "Resistance (ohm)",
        "editor.sources.notes": "Notes",
        "editor.sources.tags": "Tags",
        "editor.sources.no_waveform": "<none>",
        "editor.sources.no_waveform_item": "no waveform",
        "editor.sources.resistance_placeholder": "Optional; defaults to 50 ohm for voltage source",
        "editor.sources.valid": "No source-specific validation issues.",
        "editor.receivers.list_title": "Receivers",
        "editor.receivers.select": "Select a receiver to edit it.",
        "editor.receivers.identifier": "Identifier",
        "editor.receivers.position_x": "Position X (m)",
        "editor.receivers.position_y": "Position Y (m)",
        "editor.receivers.position_z": "Position Z (m)",
        "editor.receivers.outputs": "Outputs",
        "editor.receivers.outputs_placeholder": "Comma-separated components, e.g. Ez, Ex",
        "editor.receivers.notes": "Notes",
        "editor.receivers.tags": "Tags",
        "editor.receivers.valid": "No receiver-specific validation issues.",
        "editor.receivers.default_name": "receiver",
        "editor.geometry.list_title": "Geometry objects",
        "editor.geometry.select": "Select a geometry object to edit it.",
        "editor.geometry.label": "Label",
        "editor.geometry.kind": "Kind",
        "editor.geometry.material": "Material",
        "editor.geometry.smoothing": "Use dielectric smoothing",
        "editor.geometry.parameters": "Parameters",
        "editor.geometry.notes": "Notes",
        "editor.geometry.tags": "Tags",
        "editor.geometry.valid": "No geometry-specific validation issues.",
        "editor.geometry.no_material": "no material",
        "editor.geometry.box.lower_left_x": "Lower-left X",
        "editor.geometry.box.lower_left_y": "Lower-left Y",
        "editor.geometry.box.lower_left_z": "Lower-left Z",
        "editor.geometry.box.upper_right_x": "Upper-right X",
        "editor.geometry.box.upper_right_y": "Upper-right Y",
        "editor.geometry.box.upper_right_z": "Upper-right Z",
        "editor.geometry.sphere.center_x": "Center X",
        "editor.geometry.sphere.center_y": "Center Y",
        "editor.geometry.sphere.center_z": "Center Z",
        "editor.geometry.radius": "Radius",
        "editor.geometry.cylinder.start_x": "Start X",
        "editor.geometry.cylinder.start_y": "Start Y",
        "editor.geometry.cylinder.start_z": "Start Z",
        "editor.geometry.cylinder.end_x": "End X",
        "editor.geometry.cylinder.end_y": "End Y",
        "editor.geometry.cylinder.end_z": "End Z",
        "editor.preview.title": "This preview is generated from the current in-memory model with the default run configuration. Runtime-specific flags remain on the Simulation screen.",
        "editor.preview.messages_placeholder": "Validation and preview messages",
        "editor.preview.text_placeholder": "Generated gprMax input will appear here",
        "editor.preview.rebuild": "Rebuild Preview",
        "editor.preview.export": "Export Preview",
        "editor.preview.messages": "Messages",
        "editor.preview.input": "Input preview",
        "editor.preview.export_dialog": "Export Preview",
        "editor.preview.exported": "Preview exported to {destination}",
    }
)

_TRANSLATIONS["ru"].update(
    {
        "welcome.hero.eyebrow": "Рабочая среда моделирования",
        "welcome.hero.title": "Начните с проекта, а не с input-файла",
        "welcome.hero.body": "Workbench должен вести геофизика по понятному маршруту: проект, модель, расчёт, проверка результата. На этом этапе интерфейс сфокусирован на ясной навигации и тестируемом пользовательском сценарии.",
        "welcome.workflow.title": "Базовый рабочий сценарий",
        "welcome.workflow.description": "Рекомендуемый путь для тестирования текущего MVP:",
        "welcome.workflow.step1": "1. Создайте новый проект или откройте готовый пример.",
        "welcome.workflow.step2": "2. Настройте область модели, материалы, источники и приёмники.",
        "welcome.workflow.step3": "3. Проверьте input preview и запустите расчёт.",
        "welcome.workflow.step4": "4. Откройте результаты и проверьте A-scan или B-scan preview.",
        "welcome.examples.title": "Тестовые примеры",
        "welcome.examples.description": "Эти примеры уже содержат run artifacts и подходят для быстрых walkthrough-проверок интерфейса.",
        "welcome.examples.none": "Примеры пока не обнаружены в репозитории.",
        "workspace.banner.eyebrow": "Текущее рабочее пространство",
        "workspace.banner.title.empty": "Проект не открыт",
        "workspace.banner.subtitle.empty": "Откройте существующий проект или начните с одного из встроенных examples, чтобы пройти полный сценарий.",
        "workspace.banner.meta.empty": "После открытия проекта здесь появится состояние модели, runtime и последнего запуска.",
        "workspace.banner.title.project": "{project_name}",
        "workspace.banner.subtitle.project": "Активная модель: {model_title}",
        "workspace.banner.meta.project": "Путь проекта: {project_root}",
        "workspace.metric.project_state": "Состояние проекта",
        "workspace.metric.validation": "Готовность модели",
        "workspace.metric.runtime": "Вычислительное ядро",
        "workspace.metric.activity": "Последняя активность",
        "workspace.value.no_project": "Проект не открыт",
        "workspace.value.awaiting_project": "Ожидает проект",
        "workspace.value.runtime_ready": "Runtime готов",
        "workspace.value.no_run": "Запусков ещё нет",
        "workspace.value.project_saved": "Сохранено",
        "workspace.value.project_dirty": "Есть несохранённые изменения",
        "workspace.value.validation_ready": "Можно переходить к preview и запуску",
        "workspace.value.validation_warnings": "Есть предупреждения: {warnings}",
        "workspace.value.validation_errors": "Ошибки: {errors}, предупреждения: {warnings}",
        "workspace.value.runtime_state": "{mode} • gprMax {version}",
        "workspace.value.run_active": "Идёт {status} ({run_id})",
        "workspace.value.run_last": "Последний запуск: {status} ({run_id})",
        "project.workflow_hint": "Рекомендуемый порядок: сначала задайте область и шаг сетки, затем среду, затем источники и приёмники, и только после этого переходите к preview и запуску.",
        "project.workflow_hint.empty": "Откройте проект, чтобы увидеть состояние модели и перейти к поэтапной настройке.",
        "project.metric.materials": "Материалы",
        "project.metric.waveforms": "Waveforms",
        "project.metric.sources": "Источники",
        "project.metric.receivers": "Приёмники",
        "project.metric.geometry": "Геометрия",
        "simulation.metric.mode": "Режим расчёта",
        "simulation.metric.runs": "Число прогонов",
        "simulation.metric.runtime": "Runtime",
        "simulation.metric.activity": "Состояние расчёта",
    }
)

_TRANSLATIONS["en"].update(
    {
        "welcome.hero.eyebrow": "Modelling workspace",
        "welcome.hero.title": "Start from a project, not from an input file",
        "welcome.hero.body": "Workbench should guide a geophysicist through a clear workflow: project, model, simulation, and result review. This UI phase focuses on navigation clarity and a testable end-to-end user journey.",
        "welcome.workflow.title": "Core workflow",
        "welcome.workflow.description": "Recommended path for testing the current MVP:",
        "welcome.workflow.step1": "1. Create a new project or open a bundled example.",
        "welcome.workflow.step2": "2. Configure the model domain, materials, sources, and receivers.",
        "welcome.workflow.step3": "3. Review the input preview and start the simulation.",
        "welcome.workflow.step4": "4. Open the results and inspect the A-scan or B-scan preview.",
        "welcome.examples.title": "Example projects",
        "welcome.examples.description": "These examples already include run artifacts and are useful for quick walkthrough testing.",
        "welcome.examples.none": "No example projects were found in the repository.",
        "workspace.banner.eyebrow": "Current workspace",
        "workspace.banner.title.empty": "No project open",
        "workspace.banner.subtitle.empty": "Open an existing project or start from one of the bundled examples to walk through the full workflow.",
        "workspace.banner.meta.empty": "Project, runtime, and latest run context will appear here once a project is open.",
        "workspace.banner.title.project": "{project_name}",
        "workspace.banner.subtitle.project": "Active model: {model_title}",
        "workspace.banner.meta.project": "Project path: {project_root}",
        "workspace.metric.project_state": "Project state",
        "workspace.metric.validation": "Model readiness",
        "workspace.metric.runtime": "Execution engine",
        "workspace.metric.activity": "Latest activity",
        "workspace.value.no_project": "No project open",
        "workspace.value.awaiting_project": "Waiting for a project",
        "workspace.value.runtime_ready": "Runtime ready",
        "workspace.value.no_run": "No runs yet",
        "workspace.value.project_saved": "Saved",
        "workspace.value.project_dirty": "Unsaved changes",
        "workspace.value.validation_ready": "Ready for preview and execution",
        "workspace.value.validation_warnings": "Warnings: {warnings}",
        "workspace.value.validation_errors": "Errors: {errors}, warnings: {warnings}",
        "workspace.value.runtime_state": "{mode} • gprMax {version}",
        "workspace.value.run_active": "{status} in progress ({run_id})",
        "workspace.value.run_last": "Last run: {status} ({run_id})",
        "project.workflow_hint": "Recommended order: define the domain and spatial step first, then materials, then sources and receivers, and only then move to preview and execution.",
        "project.workflow_hint.empty": "Open a project to see the model status and continue with the staged setup flow.",
        "project.metric.materials": "Materials",
        "project.metric.waveforms": "Waveforms",
        "project.metric.sources": "Sources",
        "project.metric.receivers": "Receivers",
        "project.metric.geometry": "Geometry",
        "simulation.metric.mode": "Run mode",
        "simulation.metric.runs": "Model runs",
        "simulation.metric.runtime": "Runtime",
        "simulation.metric.activity": "Execution state",
    }
)
